FROM node:lts-alpine as base
WORKDIR /srv

FROM base as builder
WORKDIR /srv
COPY . .
RUN npm install --no-scripts
RUN npm run build

FROM base as runner
WORKDIR /srv
COPY --from=builder /srv/entrypoint.sh /srv/package*.json ./
COPY --from=builder /srv/dist/src/ ./
RUN npm ci --no-scripts --omit=dev
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
