FROM node:lts-alpine as base
WORKDIR /srv
ENV NODE_ENV production

FROM base as builder
RUN apk add curl
RUN curl -sf https://gobinaries.com/tj/node-prune | sh
COPY . .
RUN yarn install --prod
RUN yarn build
RUN node-prune

FROM base as runner
COPY --from=builder /app/entrypoint.sh .
COPY --from=builder /app/dist/src .
COPY --from=builder /app/node_modules .
RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
